[project]
name = "atticus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "ipykernel>=7.2.0",
    "pdfplumber>=0.11.9",
    "python-docx>=1.2.0",
    "pydantic-settings>=2.13.1",
    "groq>=1.1.1",
    "tiktoken>=0.12.0",
    "qdrant-client>=1.17.1",
    "elasticsearch>=9.3.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "ipykernel>=7.2.0",
    "pytest>=8.4.2",
]
